# Generated by Django 5.0.1 on 2024-01-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopapp", "0007_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="orderid",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
